namespace Wikman.Synthesizer.Editor
{
    internal static class TemplateDefaults
    {
        public static readonly EffectParameters Pickup = new EffectParameters
        {
            waveType = 2,
            masterVolume = 0,
            attackTime = 0,
            sustainTime = 0.0429497f,
            sustainPunch = 0.4645619f,
            decayTime = 0.2843174f,
            compressionAmount = 0,
            startFrequency = 0.833f,
            minFrequency = 0.3f,
            slide = 0,
            deltaSlide = 0,
            vibratoDepth = 0,
            vibratoSpeed = 0,
            overtones = 0,
            overtoneFalloff = 0,
            changeRepeat = 0,
            changeAmount = 0.5f,
            changeSpeed = 0.578f,
            changeAmount2 = 0,
            changeSpeed2 = 0,
            squareDuty = 0,
            dutySweep = 0,
            repeatSpeed = 0,
            flangerOffset = 0,
            flangerSweep = 0,
            lpFilterCutoff = 1f,
            lpFilterCutoffSweep = 0,
            lpFilterResonance = 0,
            hpFilterCutoff = 0,
            hpFilterCutoffSweep = 0,
            bitCrush = 0,
            bitCrushSweep = 0
        };
        
        public static EffectParameters Laser = new EffectParameters
        {
            waveType = 0, 
            masterVolume = 0f, 
            attackTime = 0f, 
            sustainTime = 0.2727396f, 
            sustainPunch = 0f, 
            decayTime = 0.267f, 
            compressionAmount = 0.3f, 
            startFrequency = 0.859708f, 
            minFrequency = 0.2f, 
            slide = -0.2799682f, 
            deltaSlide = 0f, 
            vibratoDepth = 0f, 
            vibratoSpeed = 0f, 
            overtones = 0f, 
            overtoneFalloff = 0f, 
            changeRepeat = 0f, 
            changeAmount = 0f, 
            changeSpeed = 0f, 
            changeAmount2 = 0f, 
            changeSpeed2 = 0f, 
            squareDuty = 0.745602f, 
            dutySweep = -0.6456483f, 
            repeatSpeed = 0f, 
            flangerOffset = 0f, 
            flangerSweep = 0f, 
            lpFilterCutoff = 1f, 
            lpFilterCutoffSweep = 0f, 
            lpFilterResonance = 0f, 
            hpFilterCutoff = 0.007859196f, 
            hpFilterCutoffSweep = 0f, 
            bitCrush = 0f, 
            bitCrushSweep = 0f
        };
        
        public static EffectParameters Explosion = new EffectParameters
        {
            waveType = 3,
            masterVolume = 0,
            attackTime = 0,
            sustainTime = 0.314821f,
            sustainPunch = 0.5657007f,
            decayTime = 0.05622197f,
            compressionAmount = 0,
            startFrequency = 0.455965f,
            minFrequency = 0,
            slide = -0.2836664f,
            deltaSlide = 0,
            vibratoDepth = 0,
            vibratoSpeed = 0,
            overtones = 0,
            overtoneFalloff = 0,
            changeRepeat = 0,
            changeAmount = -0.6271078f,
            changeSpeed = 0.8444207f,
            changeAmount2 = 0,
            changeSpeed2 = 0,
            squareDuty = 0,
            dutySweep = 0,
            repeatSpeed = 0,
            flangerOffset = 0,
            flangerSweep = 0,
            lpFilterCutoff = 1f,
            lpFilterCutoffSweep = 0,
            lpFilterResonance = 0,
            hpFilterCutoff = 0,
            hpFilterCutoffSweep = 0,
            bitCrush = 0,
            bitCrushSweep = 0
        };
        
        public static EffectParameters PowerUp = new EffectParameters
        {
            waveType = 1,
            masterVolume = 0,
            attackTime = 0,
            sustainTime = 0.1461161f,
            sustainPunch = 0,
            decayTime = 0.3097053f,
            compressionAmount = 0,
            startFrequency = 0.4444835f,
            minFrequency = 0,
            slide = 0.3679471f,
            deltaSlide = 0,
            vibratoDepth = 0,
            vibratoSpeed = 0,
            overtones = 0,
            overtoneFalloff = 0,
            changeRepeat = 0,
            changeAmount = 0,
            changeSpeed = 0,
            changeAmount2 = 0,
            changeSpeed2 = 0,
            squareDuty = 0,
            dutySweep = 0,
            repeatSpeed = 0.4591507f,
            flangerOffset = 0,
            flangerSweep = 0,
            lpFilterCutoff = 1,
            lpFilterCutoffSweep = 0,
            lpFilterResonance = 0,
            hpFilterCutoff = 0,
            hpFilterCutoffSweep = 0,
            bitCrush = 0,
            bitCrushSweep = 0
        };
        
        public static EffectParameters Hit = new EffectParameters
        {
            waveType = 0,
            masterVolume = 0,
            attackTime = 0,
            sustainTime = 0.04773384f,
            sustainPunch = 0,
            decayTime = 0.1561803f,
            compressionAmount = 0,
            startFrequency = 0.6782437f,
            minFrequency = 0,
            slide = -0.5867826f,
            deltaSlide = 0,
            vibratoDepth = 0,
            vibratoSpeed = 0,
            overtones = 0,
            overtoneFalloff = 0,
            changeRepeat = 0,
            changeAmount = 0,
            changeSpeed = 0,
            changeAmount2 = 0,
            changeSpeed2 = 0,
            squareDuty = 0.2209624f,
            dutySweep = 0,
            repeatSpeed = 0,
            flangerOffset = 0,
            flangerSweep = 0,
            lpFilterCutoff = 1,
            lpFilterCutoffSweep = 0,
            lpFilterResonance = 0,
            hpFilterCutoff = 0.2812528f,
            hpFilterCutoffSweep = 0,
            bitCrush = 0,
            bitCrushSweep = 0
        };
        
        public static EffectParameters Jump = new EffectParameters
        {
            waveType = 0, 
            masterVolume = 1f, 
            attackTime = 0f, 
            sustainTime = 0.1949434f, 
            sustainPunch = 0f, 
            decayTime = 0.2185811f, 
            compressionAmount = 0.3f, 
            startFrequency = 0.4825336f, 
            minFrequency = 0f, 
            slide = 0.2329015f, 
            deltaSlide = 0f, 
            vibratoDepth = 0f, 
            vibratoSpeed = 0f, 
            overtones = 0f, 
            overtoneFalloff = 0f, 
            changeRepeat = 0f, 
            changeAmount = 0f, 
            changeSpeed = 0f, 
            changeAmount2 = 0f, 
            changeSpeed2 = 0f, 
            squareDuty = 0.2997636f, 
            dutySweep = 0f, 
            repeatSpeed = 0f, 
            flangerOffset = 0f, 
            flangerSweep = 0f, 
            lpFilterCutoff = 0.7284591f, 
            lpFilterCutoffSweep = 0f, 
            lpFilterResonance = 0f, 
            hpFilterCutoff = 0.1255572f, 
            hpFilterCutoffSweep = 0f, 
            bitCrush = 0f, 
            bitCrushSweep = 0f
        };
        
        public static EffectParameters Blip = new EffectParameters
        {
            waveType = 2, 
            masterVolume = 0f, 
            attackTime = 0f, 
            sustainTime = 0.05993127f, 
            sustainPunch = 0.4964458f, 
            decayTime = 0.1200687f, 
            compressionAmount = 0.3f, 
            startFrequency = 0.4370109f, 
            minFrequency = 0f, 
            slide = 0f, 
            deltaSlide = 0f, 
            vibratoDepth = 0f, 
            vibratoSpeed = 0f, 
            overtones = 0f, 
            overtoneFalloff = 0f, 
            changeRepeat = 0f, 
            changeAmount = 0f, 
            changeSpeed = 0f, 
            changeAmount2 = 0f, 
            changeSpeed2 = 0f, 
            squareDuty = 0f, 
            dutySweep = 0f, 
            repeatSpeed = 0f, 
            flangerOffset = 0f, 
            flangerSweep = 0f, 
            lpFilterCutoff = 1f, 
            lpFilterCutoffSweep = 0f, 
            lpFilterResonance = 0f, 
            hpFilterCutoff = 0f, 
            hpFilterCutoffSweep = 0f, 
            bitCrush = 0f, 
            bitCrushSweep = 0f
        };

        public static EffectParameters FullSpectrum = new EffectParameters
        {
            waveType = 7, 
            masterVolume = 1, 
            attackTime = 0.1506206f, 
            sustainTime = 0.691893f, 
            sustainPunch = 0.01994733f, 
            decayTime = 0.4739512f, 
            compressionAmount = 0.5069998f, 
            startFrequency = 0.5001932f, 
            minFrequency = 0f, 
            slide = 4.397102E-06f, 
            deltaSlide = 0.2851632f, 
            vibratoDepth = 0.2112865f, 
            vibratoSpeed = 0.5671099f, 
            overtones = 0.01740607f, 
            overtoneFalloff = 0.9287476f, 
            changeRepeat = 0.2599886f, 
            changeAmount = -0.08959877f, 
            changeSpeed = 0.8291563f, 
            changeAmount2 = 0.4620606f, 
            changeSpeed2 = 0.8258253f, 
            squareDuty = 0.8705357f, 
            dutySweep = -0.9998882f, 
            repeatSpeed = 0f, 
            flangerOffset = -0.9994591f, 
            flangerSweep = -0.9882746f, 
            lpFilterCutoff = 0.9900467f, 
            lpFilterCutoffSweep = 0.1244491f, 
            lpFilterResonance = 0.9696323f, 
            hpFilterCutoff = 1.134958E-05f, 
            hpFilterCutoffSweep = 0.4106413f, 
            bitCrush = 2.354379E-05f, 
            bitCrushSweep = -0.9917902f, 
        };        
    }
}
